---
title: "Assignment 4"
output: html_document
---

Complete the following steps, using data on cities and towns in the US, `area_data.Rds`
 
1. Prep the data for analysis by creating a training dataset with 75 percent of the data and a testing dataset with 25 percent of the data.  
1. Plot home ownership `perc_homeown` (dependent variable) as a function of college education `college_educ` and comment on what you see.
1. Run a regression of home ownership on college education (home ownership is the dependent variable, percent college educated is the independent variable). 
1. Summarize the relationship between home ownership and college education in a sentence.
1. Calculate the root mean squared error from the  above model *in the testing dataset* and comment on what it means.
1. Add the variable for income to the above regression and repeat steps 3-5. 
1. Add the variable for census division (`division`) to your model and again repeat steps 3-5.

## About the Data

This data comes from the American Community Survey of 2019. It covers all of the [metro or micro
statistical areas](https://www.census.gov/programs-surveys/metro-micro/about.html#:~:text=The%20general%20concept%20of%20a,social%20integration%20with%20that%20core.) in the United States. It includes characteristics of these areas, include education, income, home ownership and others as described below.  

| Name  | Description   |
|---|---|
| name   | Name of Micro/Metro Area   |
| college_educ   | Percent of population with at least a bachelor's degree   |
| perc_commute_30p   | Percent of population with commute to work of 30 minutes or more   |
| perc_insured  | Percent of population with health insurance   |
| perc_homeown  | Percent of housing units owned by occupier   |
| geoid | Geographic FIPS Code (id) |
| income_75  | Percent of population with income over 75,000   |
| perc_moved_in   | Percent of population that moved from another state in last year   |
|  perc_in_labor force  | Percent of population in labor force   |
| metro | Metropolitan Area? Yes/No |
| state  | State Abbreviation |
| region  | Census Region |
| division | Census Division|

