---
title: "Estimating Impacts of Policy Changes"
author: "Will Doyle"
date: "r Sys.Date()"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
library(knitr)
```


```{r}
ad<-read_rds("admit_data.rds")
```


## Data Wrangling
```{r}
ad_sub <- ad %>%
  mutate(yield_f = as_factor(ifelse(yield == 1, "Yes", "No"))) %>%
  mutate(yield_f = relevel(yield_f, ref = "No")) %>% ## This is what I forgot last time
  select(ID,
         yield_f,
         legacy,
         visit,
         registered,
         sent_scores,
         sat,
         income,
         gpa,
         distance,
         net_price)
```


## Set Resamples
```{r}
ad_rs<-mc_cv(ad_sub,times=100)
```


## Settting the Model

```{r}
penalty_spec<-.1

mixture_spec<-1

lasso_logit_mod<- 
  logistic_reg(penalty=penalty_spec,
             mixture=mixture_spec) %>% 
  set_engine("glmnet")%>%
  set_mode("classification")
  
```


## Formula and Recipe
```{r}
admit_formula <- as.formula(
                        "yield_f~.")

admit_recipe<-recipe(admit_formula,ad_sub)%>%
  update_role(ID, new_role = "id variable")%>%
  step_log(distance)
```


## Workflow
```{r}
ad_wf<-workflow()%>%
  add_model(lasso_logit_mod)%>%
  add_recipe(admit_recipe)
```

## Fit the Model: THIS WILL TAKE A FEW SECONDS, JUST BREATHE . . . 
```{r}
ad_lasso_fit<-ad_wf%>%
  fit_resamples(ad_rs)
```

```{r}
ad_lasso_fit%>%
  collect_metrics()
```


```{r}
ad_lasso_fit%>%
  unnest(.metrics)%>%
  filter(.metric=="roc_auc")%>%
  ggplot(aes(x=.estimate))+
  geom_density()
```


## Finalize Workflow
```{r}
ad_lasso_final <- finalize_workflow(ad_wf,
                                      select_best(ad_lasso_fit,metric="roc_auc")) %>%
  fit(ad_sub)
```

## Parameter Estimates
```{r}
ad_lasso_final%>%
  extract_fit_parsnip()%>%
  tidy()%>%
  kable()
```

## Hyperparameter Tuning


## Set Up Lasso Model

```{r}
lasso_logit_mod<- 
  logistic_reg(penalty=tune(),
             mixture=mixture_spec) %>% 
  set_engine("glmnet")%>%
  set_mode("classification")
```


## Set Grid
```{r}
lasso_grid<-grid_regular(parameters(lasso_tune_fit) ,levels=10)
```



## Update Model

```{r}
ad_wf<-ad_wf%>%
  update_model(lasso_logit_mod)
```

```{r}


```


